# .github/workflows/publish.yml
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tag push

permissions:
  id-token: write  # Required for Trusted Publisher to PyPI
  contents: read

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1