# .github/workflows/publish.yml
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # 当你 push 一个如 v1.0.0 的 tag 时触发

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
